name: 🐍 Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Geração da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: gabriellsx
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit da cobrinha
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "🐍 animação da cobrinha atualizada"
          add: "dist/github-contribution-grid-snake.svg"

      - name: Publicar como GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
